### ISSUE TITLE
save file with utf8 encoding

### ISSUE THREAD

**Issue by walkthetalk** [texmacs/devel#7]
for Chinese character, it will translated into 4 hex characters.
maybe use utf8 directly will be more friendly.

I found discussion in https://lists.gnu.org/archive/html/texmacs-dev/2012-09/msg00014.html.
any progress?

**Comment by mgubi** [comment]
There are no plan in the short term to switch to utf8. I do not think it is a priority. You need to consider .tm files as binary files, they are not supposed to be edited by hand. On the same lines you do not expect to be able to open into a text editor a PDF file. Can you explain what is the use-case that lead you to this request?

**Comment by walkthetalk** [comment]
just for file size, for Chinese, one character result in six even seven bytes.
