### ISSUE TITLE
can texmacs do vertical typesetting?

### ISSUE THREAD

**Issue by walkthetalk** [texmacs/devel#8]
for Chinese ancient books, main typesetting direction is vertical, do we support it?
and related ruby / warichu?

**Comment by mgubi** [comment]
I do not think that TeXmacs supports this style of typesetting. It would require large changes I imagine and unless somebody is interested in implementing it I'm not sure it is going to happen. Do you have examples of software which can do it? Some TeX package/version? It would be interesting to have examples of working software capable of achieving what you expect.

**Comment by walkthetalk** [comment]
latex example:
https://github.com/NSKernel/IntroductionToCalculus

for conTex, as I know, someone use rotation to get vertical result:
i.e. rotate character by 90degree  counterclockwise  , and then rotate
paragraph 90degree clockwise.

**Comment by mgubi** [comment]
Very interesting! I see what seems to be formulas which are typesetted "on the side", is this correct? What is the convention to typeset mathematics in this top-down writing order? What is also the right order for reading, from left to right or the other way around?

**Comment by walkthetalk** [comment]
for chinese, it is right to left, and top to down. maybe we can implement
any direction by rotation transform.
