### ISSUE TITLE
Update Guile support to work with 2.2 and 3.x series

### ISSUE THREAD

**Issue by XVilka** [texmacs/devel#9]
Packaged Guile in many Linux distributions versions are very old, GNU Guile 3.0.x series is available for a while already:

- https://www.gnu.org/software/guile/download
- https://www.gnu.org/software/guile/news/gnu-guile-300-released.html
- https://www.gnu.org/software/guile/news/gnu-guile-301-released.html
- https://www.gnu.org/software/guile/news/gnu-guile-302-released.html
- https://www.gnu.org/software/guile/news/gnu-guile-303-released.html
- https://www.gnu.org/software/guile/news/gnu-guile-304-released.html
- https://ftp.gnu.org/gnu/guile/guile-3.0.4.tar.gz

3.0.0 version is the new stable series and includes a lot of various improvements, among them - the huge performance increase, since JIT employment: https://www.gnu.org/software/guile/news/gnu-guile-300-released.html

Compared to 2.2, microbenchmark performance is around twice as good on the whole, though some individual benchmarks are up to 32 times as fast. Other new features in 3.0 include support for interleaved definitions and expressions in lexical contexts, native support for structured exceptions, better support for the R6RS and R7RS Scheme standards, along with a pile of optimizations.

Texmacs is being the sole reason Linux distributions can't upgrade default Guile version to 3.0: https://bugzilla.redhat.com/show_bug.cgi?id=1828124 (see the latest comment from Tomas Korbar)

**Comment by pireddag** [comment]
I became aware of this issue through a Hacker news thread. I am not one of the developers, but as far as I know they are working to replace Guile 1.8
@mgubi might be able to tell you more.

**Comment by mgubi** [comment]
I answered directly here: https://bugzilla.redhat.com/show_bug.cgi?id=1828124 . There are no short term plans to go to Guile 3, this will require still more time and efforts and it is not clear we want to do it due to performance concerns.
